---
# This playbook deploys the whole application stack in this site.  

- name: become timecapsule
  hosts: nas
  become: true

  roles:
    - basic
    - mailalarm
    - timecapsule
    - plex
    - glancesweb
    - printerupload
    - syncthing
