---
# This playbook contains common plays that will be run on all nodes.

- name: Install samba
  apt: name=samba state=present

- name: configure Samba
  template: src=smb.conf dest=/etc/samba/smb.conf

- service: name=smbd state=restarted
