---

- name: Check if plex is installed
  command: dpkg-query -W plex
  register: plex_check_deb
  failed_when: plex_check_deb.rc > 1
  changed_when: plex_check_deb.rc == 1

- name: Download plex
  get_url: 
    url="https://downloads.plex.tv/plex-media-server/1.0.0.2261-a17e99e/plexmediaserver_1.0.0.2261-a17e99e_amd64.deb"
    dest="/tmp/plex.deb"
  when: plex_check_deb.rc == 1

- name: Install plex
  apt: deb="/tmp/plex.deb"
  sudo: true
  when: plex_check_deb.rc == 1
