---

- apt_key: url=https://downloads.plex.tv/plex-keys/PlexSign.key state=present
- apt_repository: repo='deb https://downloads.plex.tv/repo/deb public main' state=present
- apt: name=plexmediaserver update_cache=yes state=present
